spring.application.name=AUDIT-SERVICE
server.port=${PORT:8085}

# GCP Cloud SQL Connection String Configuration
spring.datasource.url=jdbc:mysql:///${DB_NAME:auditdb}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=${DB_USER}&password=${DB_PASS}&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate Cloud Dialect Setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Disable Eureka Discovery and Registration for Cloud Profile
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
